---

- hosts: all
  gather_facts: false
  vars:
    loop_count: 1000
    sleep_length: 1
  tasks:
    - name: Output
      shell: 'echo "hello world" && sleep {{ sleep_length }}'
      with_sequence: count="{{ loop_count }}"
